spring:
    datasource:
        url: jdbc:mysql://localhost:3306/basic_1?useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: chzh1012
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            properties:
                hibernate.format_sql: true
        database-platform: org.hibernate.dialect.MySQLDialect